services:
  - type: web
    name: projeto-mvc-firebase
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
